DEalog/backoffice

- CHANGELOG.md
- mix.exs
This PR bumps the version and updates the changelog for the 0.3.0 release.
> Prepare release v0.3.0

- .github/workflows/dev-deployment.yml
- .github/workflows/docker-build.yml
- .github/workflows/elixir.yml
- CHANGELOG.md
- dev
This PR adds changes for switching the default branch from `master` to `main`.
Changes are:
* `dev` script adaptions
* GH action adaptions
> Change default branch from master to main

- .github/workflows/deploy.yml
This PR fixes the cluster name.
Relates to DEV-100
> Fix deployment (DEV-100)

- CHANGELOG.md
This PR adds a changelog entry for AWS deployment.
Relates to DEV-100
> Update changelog (DEV-100)

- .github/workflows/deploy.yml
Fix deploy job
Relates to DEV-166
> use updated task definition on deployment job

- CHANGELOG.md
- docker-compose.yml
- lib/dealog_backoffice_web/templates/layout/root.html.leex
- lib/dealog_backoffice_web/views/layout_view.ex
This PR adds some anonymous tracking to get some metrics of usage.
Relates to DEV-148
> Add anonymous tracking via Plausible (DEV-148)

- .github/Dockerfile
- .github/workflows/build-test-and-publish.yml
- CHANGELOG.md
- Dockerfile
This PR adds the missing README.md file to the Docker release.
Relates to DEV-160
> Add README to Docker releases (DEV-160)

- .github/workflows/deploy.yml
This fixes wrong syntax for env vars.
Relates to DEV-178
> Fix AWS deployment (DEV-178)

- CHANGELOG.md
- config/dev.exs
- lib/dealog_backoffice/messages/projectors/message_service.ex
- lib/dealog_backoffice/middlewares/log.ex
- lib/dealog_backoffice/router.ex
This PR introduces enhanced logging.
Relates to DEV-157
> Improve logging (DEV-157)

- CHANGELOG.md
- lib/dealog_backoffice_web/templates/layout/app.html.eex
This PR centers all user related screens when logged out.
Relates to DEV-161
> Center login and user screens (DEV-161)

- CHANGELOG.md
- config/test.exs
- lib/dealog_backoffice/accounts.ex
- lib/dealog_backoffice/accounts/projections/account.ex
- lib/dealog_backoffice/accounts/projectors/account.ex
- lib/dealog_backoffice_web/live/settings/accounts/form_component.html.leex
- lib/dealog_backoffice_web/live/settings/accounts/form_data.ex
- lib/dealog_backoffice_web/live/settings/index.ex
- lib/dealog_backoffice_web/live/settings/index.html.leex
- priv/repo/migrations/20201123101328_add_administrative_area_association_to_account_projection.exs
- test/dealog_backoffice/accounts_test.exs
This PR changes how the administrative area (referenced by ars) is being preloaded.
Relates to DEV-181
> Change preloading administrative areas (DEV-181)

- .github/Dockerfile
- .github/workflows/build-test-and-publish.yml
- Dockerfile
- docker/web/Dockerfile
This PR streamlines and updates the Docker images (Elixir and Alpine).
Relates to DEV-199
> Update Docker images (DEV-199)

- .github/Dockerfile
- .github/workflows/build-test-and-publish.yml
- Dockerfile
This reverts commit 0d2bdfc39e15eb28418006c7ea1cb2876b66b8aa.
> Revert "Update Docker images (DEV-199) (#74)"

- CHANGELOG.md
- config/prod.exs
- config/releases.exs
- lib/dealog_backoffice_web/endpoint.ex
This PR changes the prod config to enable AWS deployments
> Change prod config (DEV-202)

- CHANGELOG.md
- config/releases.exs
This PR adds the check origin configuration for AWS
> Add check origin configuration (DEV-202)

- CHANGELOG.md
- config/releases.exs
This PR adds debugging information for AWS.
> Add logging to prod config (DEV-202)

- config/releases.exs
- lib/dealog_backoffice_web/endpoint.ex
Change live_view socket to support long polling.
> Change live_view socket config (DEV-202)

- lib/dealog_backoffice_web/live/components/change_entry_component.html.leex
The PR fixes a wrong action name.
Relates to DEV-185
> Fix action name for changed message (DEV-185)

- CHANGELOG.md
- lib/dealog_backoffice_web/views/auth_helpers.ex
This PR adds back the actions for messages.
Relates to DEV-208
> Fix wrongly disabled actions to be shown again (DEV-208)

- assets/tailwind.config.js
- assets/yarn.lock
- lib/dealog_backoffice_web/live/components/notification_error.html.leex
- lib/dealog_backoffice_web/live/components/notification_success.html.leex
- lib/dealog_backoffice_web/templates/layout/live.html.leex
This PR changes the layout to a maximum width as well as the notification to have a slight transparency.
Also the Javascript dependencies are updated.
Relates to DEV-179
> Change layout to make notification less intrusive (DEV-179)

- CHANGELOG.md
- mix.exs
This PR prepares the release of v0.5.0
Relates to DEV-210
> Prepare release 0.5.0 (DEV-210)

- CHANGELOG.md
- mix.exs
This PR bumps to the next dev version.
Relates to DEV-210
> Prepare 0.6.0-dev (DEV-210)

- CHANGELOG.md
- lib/dealog_backoffice/release.ex
- rel/run.sh
This PR adds event store migrations.
Relates to DEV-209
> Add event store migration task (DEV-209)

- assets/yarn.lock
This PR updates the frontend related dependencies.
Relates to DEV-209
> Update Javascript dependencies (DEV-209)

- .github/workflows/build-test-and-publish.yml
This PR tries to fix the deployment of wrong images race condition.
Relates to DEV-203
> Change action to only push Docker image on merged PR (DEV-203)

- .github/workflows/build-test-and-publish.yml
This tries to fix the deployment.
Relates to DEV-203
> Change build and push detection (DEV-203)

- .github/dependabot.yml
This PR introduces a dependabot configuration for Elixir, Javascript, Docker and GH actions.
Relates to DEV-212
> Add dependabot config (DEV-212)

- .github/Dockerfile
- .github/dependabot.yml
- .github/workflows/build-test-and-publish.yml
- Dockerfile
- docker/web/Dockerfile
This PR combines the updates to the Docker images detected by dependabot
Relates to DEV-213
> Update docker images (DEV-213)

- assets/package.json
- assets/webpack.config.js
- assets/yarn.lock
This PR updates several outdated NodeJS / Javascript dependencies detected by Dependabot
Relates to DEV-216
> Update NodeJS / Javascript dependencies (DEV-216)

- assets/yarn.lock
- dev
This PR updates @babel/core which became a stuck Dependabot PR.
Relates to DEV-216
> Update stuck node dependency (DEV-216)

- assets/package.json
- assets/yarn.lock
This PR removes SASS as it is not used.
Relates to DEV-218
> Remove SASS (DEV-218)

- assets/package.json
- assets/postcss.config.js
- assets/tailwind.config.js
- assets/yarn.lock
This PR updates FE dependencies and adjust configs
Relates to DEV-226
> Update frontend dependencies (DEV-226)

- CHANGELOG.md
- lib/dealog_backoffice/messages/projections/archived_message.ex
- lib/dealog_backoffice/messages/projections/deleted_message.ex
- lib/dealog_backoffice/messages/projections/message.ex
- lib/dealog_backoffice/messages/projections/message_for_approval.ex
- lib/dealog_backoffice/messages/projectors/archived_message.ex
- lib/dealog_backoffice/messages/projectors/deleted_message.ex
- lib/dealog_backoffice/messages/projectors/message.ex
- lib/dealog_backoffice/messages/projectors/message_approval.ex
- priv/repo/migrations/20210902184541_add_ars_and_organization_to_projections.exs
This PR adds projecting ARS and organization to projections for filtering
Relates to DEV-219
> Add projecting ars and organization to projections (DEV-219)

- CHANGELOG.md
- assets/package.json
- assets/tailwind.config.js
- assets/yarn.lock
- lib/dealog_backoffice_web/live/message_approvals/form_component.html.leex
- lib/dealog_backoffice_web/live/organization_messages/form_component.html.leex
- lib/dealog_backoffice_web/live/settings/accounts/form_component.html.leex
This PR fixes the form field styles.
Relates to DEV-229
> Fix form field styles (DEV-229)

- CHANGELOG.md
- lib/dealog_backoffice/messages.ex
- lib/dealog_backoffice/messages/queries/list_message_approvals_by_administrative_area.ex
- lib/dealog_backoffice/messages/queries/list_messages_by_administrative_area.ex
- lib/dealog_backoffice_web/live/message_approvals/index.ex
- lib/dealog_backoffice_web/live/organization_messages/index.ex
- priv/translations/web/de/LC_MESSAGES/default.po
- priv/translations/web/default.pot
This PR adds a filter for the current user's administrative area to my organization and message approvals.
Relates to DEV-220
> Add filter for administrative area (DEV-220)
